services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: licitacao360_backend
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_licitacao360.wsgi:application --bind 0.0.0.0:8000 --timeout 600 --workers 2 --threads 4
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=@cemos2028
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:18
    container_name: postgres_licitacao
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ðŸ”¹ Nginx reverso principal com proxy para Django e servindo Angular
  nginx:
    image: nginx:latest
    container_name: licitacao_nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "8088:8088"
      - "443:443"
    volumes:
      # FRONTEND 1 â€“ LICITACAO360    
      - ./frontend-licitacao/dist/frontend/browser:/usr/share/nginx/licitacao
      # NGINX CONFIG
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # ACME challenge (Let's Encrypt HTTP-01)
      - ./certbot/www:/var/www/certbot
      # SSL
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # DJANGO STATIC
      - static_volume:/static
    networks:
      - app_network


volumes:
  static_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge